### ISSUE TITLE
error entering edit mode for a sentence

### ISSUE THREAD

**Issue by nschneid** [nschneid/activedop#48]
<img width="756" alt="image" src="https://github.com/user-attachments/assets/bec56c62-5de5-4e2e-a33a-8fa8bf6ec04f">

The sentence: "just sitting here thinking about it I would estimate that there are over 600 billion species of insect in my basement alone which _. is a real puzzle because we pay 16 $ a month to have a man come and spray an allegedly lethal chemical all over the place"

**Comment by nschneid** [comment]
This looks like the problem:

```
 :Head (D :t "16" :p "$"))
                    :Head (Nom
                        :Head (N)))
```

**Comment by bwaldon** [comment]
This error was due to the old regime of punctuation handling: [handle_punctuation()](https://github.com/bwaldon/activedop/blob/d3c8dc486051e96e8469e8c9793226c34fce2565/app.py#L1501C5-L1501C23) identified initial/trailing punctuation sequences on terminal nodes, via a regex query that would always treat `$` on its own as trailing punctuation of the preceding terminal node. At that point, `$` would be stripped its original position (leading to an illicit 'empty' terminal) and treated as a `:p` tag of the preceding terminal. 

We shouldn't see this behavior after https://github.com/nschneid/activedop/commit/c349d9b2aef192b28d519d6e5f3f90ae69304e36 (and I just loaded your sentence into activedop edit mode w/ no issues), so I think we can close this issue.
