### ISSUE TITLE
IndexError for sentence navigation

### ISSUE THREAD

**Issue by nschneid** [nschneid/activedop#66]
When navigating to sentence 1, or when continuing past the last sentence:
<img width="1043" alt="image" src="https://github.com/user-attachments/assets/fd1c608c-edc0-4c66-a5ad-aa88d3a4ab59">

**Comment by bwaldon** [comment]
I am having trouble reproducing this one myself. Can you share the .csv file of sentences you were annotating?

**Comment by nschneid** [comment]
[newsentsExample.csv](https://github.com/user-attachments/files/16982360/newsentsExample.csv)

**Comment by bwaldon** [comment]
I'm unable to reproduce this, but two notes: 

- This should only happen in cases where you're navigating to a previously-annotated sentence. (Because line 550 is in scope of conditional `if annotation is not None:`, line 540). 
- The IndexError suggests that `senttok` is a tuple shorter than the # of terminals in `tree`. Out of curiosity, was Sentence 1 retokenized before you encountered this issue?

**Comment by bwaldon** [comment]
https://github.com/nschneid/activedop/pull/68 is an independently-motivated change which may address the issue

**Comment by bwaldon** [comment]
Same with https://github.com/nschneid/activedop/pull/69

**Comment by nschneid** [comment]
Yeah it appears to be fixed when I update the code!
