### ISSUE TITLE
some nonterminals missing functions in parser output (new grammar)

### ISSUE THREAD

**Issue by nschneid** [nschneid/activedop#84]
tokens: `I have said above , that the atonement is to be regarded as that by which God has bridged over the gulf which _. separated between what sin had made us , and what it was the desire of the divine love that we should become . _. _.`

<img width="380" alt="image" src="https://github.com/user-attachments/assets/2933e04a-151e-46c7-af7e-fcf53773a263">

**Comment by bwaldon** [comment]
I can reproduce this -- the problem is that `filterparsetrees()` (the function responsible for displaying parses matching user-specified constraints) is showing trees that haven't undergone the regularization via `ActivedopTree._apply_standard_labels()`, which contains a number of guardrails against producing illicit tree structures. (Including: all non-terminals -- besides the node directly below `ROOT` -- must have a function label and are assigned `Head` by default). I'll fix this. In the meantime: once the user clicks `edit` on one of the trees, the user is redirected to an edit window showing the corrected tree.
